// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6N6Bns1oBzRlvH7IvKBjwj177y6hmzDQ',
    appId: '1:702944765585:web:7d510c624f55d92c874130',
    messagingSenderId: '702944765585',
    projectId: 'railnova-c67f5',
    authDomain: 'railnova-c67f5.firebaseapp.com',
    storageBucket: 'railnova-c67f5.firebasestorage.app',
    measurementId: 'G-L5NLZY813T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qp3UwcTf2gW1LKBgSSnyxiWBKcF18Tw',
    appId: '1:702944765585:android:7c96a24dbf82afac874130',
    messagingSenderId: '702944765585',
    projectId: 'railnova-c67f5',
    storageBucket: 'railnova-c67f5.firebasestorage.app',
  );
}
